### ISSUE TITLE
LIVEFB数据集处理

### ISSUE THREAD

**Issue by bingo-G** [narthchin/DEIQT#10]
您好，根据您的对于LIVEFB的处理代码，会出现ValueError: Required crop size (224, 224) is larger than input image size (196, 500)，对于LIVEFB的数据处理部分好像并没有发现做什么特殊处理，那对于这些size小的图片是怎么处理的，或者是在筛选过size的LIVEFB数据集上进行实验的呢？

**Comment by bingo-G** [comment]
![image](https://github.com/narthchin/DEIQT/assets/78676446/e98d7a83-e566-4a51-9870-c3ae4fd87481)

看到有这个resize到224，不过release的代码是注释掉了，请问是用这种方法进行的实验吗

**Comment by narthchin** [comment]
感谢同学指出！

LIVEFB由于数据集较大的特性，我们有两种处理：
1. 使用`transforms.Resize((224, 224))`，同时注释`RandomCrop`，并设置config文件中的`PATCH_NUM: 10` -> `PATCH_NUM: 1`。
2. 保留`PATCH_NUM: 10`数据增强，同时启用`transforms.Resize`，并将分辨率设置为`(512, 384)`或其它数值。

1中的取消数据增强可能在一定程度影响性能，但LIVEFB本身数据量就很大，这部分影响十分轻微。

上传的代码可能这部分忘了做补充说明，十分感谢同学！
