### ISSUE TITLE
SPAQ数据处理

### ISSUE THREAD

**Issue by bingo-G** [narthchin/DEIQT#11]
您好，很多数据集的结果都是可复现的，但是我测试SPAQ的时候性能plcc最高也就是0.86或0.87，达不到论文中0.92左右的水平，所以请问是否对SPAQ数据做了其他特殊处理，因为我还看到有个做spaq_downsample.py的文件，是否和这个处理有关

**Comment by bingo-G** [comment]
> 您好，很多数据集的结果都是可复现的，但是我测试SPAQ的时候性能plcc最高也就是0.86或0.87，达不到论文中0.92左右的水平，所以请问是否对SPAQ数据做了其他特殊处理，因为我还看到有个做spaq_downsample.py的文件，是否和这个处理有关

而且相对于同体量的数据集，貌似spaq跑起来会慢很多

**Comment by narthchin** [comment]
同学您好，

首先感谢您对我们论文和工作的注意和投入！SPAQ数据集图像来源由于是手机拍摄的图像，相对来说复杂一些，分辨率和尺寸并不固定。而且超大尺寸的图像较多（2K甚至是4K分辨率），这些图像会给数据预处理带来较大的运算压力，特别是服务器IO速度较慢时，比如运行在HDD上。

因此我们使用`spaq_downsample.py`来先将图像降采样并保存至硬盘上。同学可以尝试此流程。

**Comment by narthchin** [comment]
在SPAQ数据集训练时，我们默认使用已经经过`spaq_downsample.py`降采样的图像，因此在`IQA/build.py`里，对于SPAQ数据集我们并没有采用Resize而是直接Crop。如果不使用`spaq_downsample.py`，此时RandomCrop会从2K、4K图像中裁剪(224, 224)，会破坏较多图像信息，因此会有性能的下降。

**Comment by bingo-G** [comment]
理解了，十分感谢您的热心回复！
